// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Item { id: bigint, base_type: string, base_line: string, raw_data: string, }