// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Item {
	verified: boolean;
	w: bigint;
	h: bigint;
	icon: string;
	support: boolean | null;
	stackSize: bigint | null;
	maxStackSize: bigint | null;
	stackSizeText: string | null;
	league: string | null;
	id: string | null;
	fractured: boolean | null;
	synthesized: boolean | null;
	name: string;
	typeLine: string;
	baseType: string;
	identified: boolean;
	itemLevel: bigint | null;
}
