// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ItemProperty {
	name: string;
	values: any[];
	display_mode: bigint;
	progress: number | null;
	type: bigint | null;
	suffix: string | null;
}
