// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Price { id: bigint, name: string, price: number, revision: bigint, fully_linked: boolean, }