// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Profile { id: bigint, name: string, league_id: string, pricing_league: string, }