// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Snapshot { id: bigint, stash_id: string, item_id: bigint, amount: bigint, }