// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Snapshot {
	id: bigint;
	profile_id: bigint;
	timestamp: number;
	pricing_revision: bigint;
}
