// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemWithPrice } from './ItemWithPrice';

export interface UseEffectResponse {
	items: Array<ItemWithPrice>;
	total_chaos: number;
	total_div: number;
}
