name: Release Workflow

on:
  release:
    types:
      - published
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: deploy-on-release
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Loothound/loothound.github.io/actions/workflows/deploy.yml/dispatches \
          -d '{"ref":"master"}'
      - uses: actions/checkout@v3